# Generated by Django 5.0.6 on 2024-06-29 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_habilidades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habilidades',
            new_name='Habilidad',
        ),
    ]
