# Generated by Django 5.0.6 on 2024-06-27 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prueba',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
